import org.jetbrains.intellij.platform.gradle.TestFrameworkType
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("java")
    id("org.jetbrains.kotlin.jvm") version "2.1.10"
    id("org.jetbrains.intellij.platform") version "2.16.0"
    id("org.jetbrains.changelog") version "2.2.1"
    // ktlint linter - read more: https://github.com/JLLeitschuh/ktlint-gradle
    // id("org.jlleitschuh.gradle.ktlint") version "10.1.0"
}
fun properties(key: String) = project.findProperty(key).toString()

val pluginGroup = properties("pluginGroup")
val pluginName_ = properties("pluginName_")
val pluginVersion = properties("pluginVersion")
val pluginSinceBuild = properties("pluginSinceBuild")
val pluginVerifierIdeVersions = properties("pluginVerifierIdeVersions")
val intellijPublishChannel = properties("intellijPublishChannel")
val intellijPublishToken = properties("intellijPublishToken")

val platformType = properties("platformType")
val platformVersion = properties("platformVersion")
val platformPlugins = properties("platformPlugins")

group = pluginGroup
version = pluginVersion
println("version: $version")
repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

intellijPlatform {
    buildSearchableOptions = false
    pluginConfiguration {
        name = pluginName_
        version = pluginVersion
        ideaVersion {
            sinceBuild = pluginSinceBuild
        }
    }
    publishing {
        token = intellijPublishToken
        channels = listOf(intellijPublishChannel, "default").filter(String::isNotEmpty).take(1)
    }
    pluginVerification {
        ides {
            create(platformType, pluginVerifierIdeVersions) {
                useInstaller = true
            }
        }
    }
}

dependencies {
    testImplementation(gradleTestKit())
    testImplementation(kotlin("test"))
    testImplementation(kotlin("test-junit"))
    intellijPlatform {
        create(platformType, platformVersion)
        testFramework(TestFrameworkType.Platform)
        platformPlugins
            .split(',')
            .map(String::trim)
            .filter(String::isNotEmpty)
            .forEach {
                if (it.contains(':')) {
                    plugin(it)
                } else {
                    bundledPlugin(it)
                }
            }
    }
}

// Read more: https://github.com/JetBrains/gradle-changelog-plugin
changelog {
    version.set(pluginVersion)
    headerParserRegex.set("""(\d+\.\d+\.\d+)""".toRegex())
}
tasks {
    properties("javaVersion").let {
        withType<JavaCompile> {
            sourceCompatibility = it
            targetCompatibility = it
        }
        withType<KotlinCompile> {
            compilerOptions.jvmTarget.set(JvmTarget.fromTarget(it))
        }
    }

    register("copyInspections") {
        doLast {
            inspections().forEach {
                write(
                    File("src/main/resources/inspectionDescriptions/" + it.file().name),
                    it.content()
                )
            }
        }
    }
    register("checkReadme") {
        doLast {
            if (readmeFile().readText() != generatedReadmeContent(readmeFile())) {
                throw GradleException("Readme is not up to date")
            }
        }
    }
    register("updateReadme") {
        doLast {
            val readme = readmeFile()
            if (write(readme, generatedReadmeContent(readme))) {
                println("Readme updated")
            }
        }
    }

    named("test") {
        dependsOn("checkReadme")
    }
    named("buildPlugin") {
        dependsOn("copyInspections")
    }
    named("runIde") {
        dependsOn("copyInspections")
    }

    // Network-sensitive tasks: run ONLY when not in --offline mode
    // You'll probaly need to prime your caches during an online phase, using a command such as:
    // ./gradlew help --refresh-dependencies --no-daemon
    matching { name in listOf("publishPlugin", "verifyPlugin") }.configureEach {
        onlyIf { !gradle.startParameter.isOffline }
    }
}

// Custom functions
fun write(file: File, content: String): Boolean {
    var result = false
    if (!file.exists()) {
        file.createNewFile()
    }
    if (file.readText() != content) {
        result = true
        file.writeText(content)
    }
    return result
}

class Descriptor(
    private val file: File,
    private val uid: String
) {
    fun uid() = uid
    fun file() = file
    fun content() = file.readText()
    fun short() = content()
        .replace(Regex("<!-- main -->(.*)", RegexOption.DOT_MATCHES_ALL), "")
        .trim()
}

fun actions() = projectHtmlFiles("Action")
fun inspections() = projectHtmlFiles("Inspection")


fun generatedReadmeContent(readme: File): String =
    readme.readText().replace(
        Regex("<!-- Autogenerated -->.+", RegexOption.DOT_MATCHES_ALL), ""
    ) + "<!-- Autogenerated -->\n" + generateSections()

fun readmeFile() = File("README.md")
fun projectHtmlFiles(type: String) = File("src/main/kotlin/com/funivan/idea/phpClean")
    .walkTopDown()
    .filter { it.name.contains("${type}.html") }
    .map {
        Descriptor(
            File(it.path),
            it.name.replace("${type}.html", "")
        )
    }

fun generateSections() = listOf(
    Pair("Inspections", inspections()),
    Pair("Actions", actions()),
).fold("") { acc, pair ->
    acc + "## ${pair.first}\n" +
            pair.second.sortedBy { it.uid() }
                .map {
                    val description = it.short().replace("<pre>", "```php").replace("</pre>", "```")
                    "#### ${it.uid()}\n$description\n"
                }
                .joinToString("") +
            "\n"
}
